/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CharactersImport } from './routes/characters'
import { Route as MoviesIndexImport } from './routes/movies/index'
import { Route as MoviesMovieIdImport } from './routes/movies/$movieId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CharactersRoute = CharactersImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MoviesIndexRoute = MoviesIndexImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRoute,
} as any)

const MoviesMovieIdRoute = MoviesMovieIdImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersImport
      parentRoute: typeof rootRoute
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdImport
      parentRoute: typeof rootRoute
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/characters': typeof CharactersRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies': typeof MoviesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/characters': typeof CharactersRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies': typeof MoviesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/characters': typeof CharactersRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/': typeof MoviesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/characters' | '/movies/$movieId' | '/movies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characters' | '/movies/$movieId' | '/movies'
  id: '__root__' | '/' | '/characters' | '/movies/$movieId' | '/movies/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CharactersRoute: typeof CharactersRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CharactersRoute: CharactersRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/characters",
        "/movies/$movieId",
        "/movies/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/characters": {
      "filePath": "characters.tsx"
    },
    "/movies/$movieId": {
      "filePath": "movies/$movieId.tsx"
    },
    "/movies/": {
      "filePath": "movies/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
